rentme/api/urls.py
# from django.conf.urls import include, url
# from rest_framework import routers
# from rest_framework.documentation import include_docs_urls
#
# from rentme.api import views

# router = routers.SimpleRouter()
# router.register(r'listing', views.ListingViewSet)
# router.register(r'agency', views.AgencyViewSet)
# API_TITLE = 'API title'
# API_DESCRIPTION = '...'

# urlpatterns = router.urls + [
    # url(r'^healthcheck$', views.HealthcheckView.as_view()),
    # # url(r'^listings/$', views.ListingList.as_view()),
    # url(r'^auth/', include('rest_framework.urls', namespace='rest_framework')),
    # # url(r'^snippets/(?P<pk>[0-9]+)$', views.snippet_detail),
    # url(r'^docs/', include_docs_urls(title=API_TITLE, description=API_DESCRIPTION)),
# ]
urlpatterns = []

rentme/data/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^localities$', views.LocalityView.as_view(), name='all-localities'),
    url(r'^localities/l/(?P<locality_id>[0-9]+)$', views.LocalityDrilldownView.as_view(), name='locality-drilldown'),
    url(r'^localities/d/(?P<district_id>[0-9]+)$', views.LocalityDrilldownView.as_view(), name='district-drilldown'),
    url(r'^localities/s/(?P<suburb_id>[0-9]+)$', views.LocalityDrilldownView.as_view(), name='suburb-drilldown'),
    url(r'^rentals/all$', views.RentalListView.as_view(), name='rentals.all'),
    url(r'^rentals/(?P<pk>[0-9]+)$', views.RentalView.as_view(), name='rentals.view'),
]

rentme/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + [
    url(r'^api/', include('rentme.api.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('rentme.data.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

rentme/api/models.py
from django.db import models

# Create your models here.

rentme/data/models/listing.py
import enum

from django.db import models

from rentme.data.models._utils import EnumIntegerField


class Agency(models.Model):

    address = models.TextField(
        null=True,
        help_text='The address of the company HQ.'
    )
    branding = models.ForeignKey(
        'Branding',
        blank=True,
        null=True,
        on_delete=models.CASCADE,
        related_name='agency_reverse_branding',
        help_text='The branding object for the company.'
    )
    city = models.TextField(
        null=True,
        help_text='The city where the company HQ is located.'
    )
    e_mail = models.TextField(
        null=True,
        help_text='A contact email address for the company.'
    )
    fax_number = models.TextField(
        null=True,
        help_text='A fax number for the company.'
    )
    id = models.IntegerField(
        primary_key=True,
        help_text='The ID of the company.'
    )
    is_job_agency = models.NullBooleanField(
        null=True,
        help_text='Indicates whether the agency does job listings.'
    )
    is_licensed_property_agency = models.NullBooleanField(
        null=True,
        help_text='Indicates whether the agency is an REAA licensed property '
                  'agency'
    )
    is_real_estate_agency = models.NullBooleanField(
        null=True,
        help_text='Indicates whether the agency does real estate.'
    )
    logo = models.TextField(
        null=True,
        help_text='A URL for the company logo.'
    )
    logo2 = models.TextField(
        null=True,
        help_text='A URL for the second company logo.'
    )
    name = models.TextField(
        null=True,
        help_text='The name of the company.'
    )
    phone_number = models.TextField(
        null=True,
        help_text='A contact phone number for the company. For Motors '
                  'Dealership please use the PhoneNumbers collection instead'
    )
    suburb = models.TextField(
        null=True,
        help_text='The suburb where the company HQ is located.'
    )
    website = models.TextField(
        null=True,
        help_text='The URL of the company website.'
    )


class Agent(models.Model):

    agency = models.ManyToManyField(
        'Agency',
        related_name='agents',
        help_text='The agency that this agent is contactable at.'
    )
    e_mail = models.TextField(
        null=True,
        help_text='Gets the email of the dealer'
    )
    fax_number = models.TextField(
        null=True,
        help_text='Get the fax number of a contact'
    )
    full_name = models.TextField(
        null=True,
        help_text='Get the name of a contact'
    )
    home_phone_number = models.TextField(
        null=True,
        help_text='Get the home phone number of a contact'
    )
    mobile_phone_number = models.TextField(
        null=True,
        help_text='Get the mobile phone number of a contact'
    )
    office_phone_number = models.TextField(
        null=True,
        help_text='Get the office phone number of a contact'
    )
    photo = models.TextField(
        null=True,
        help_text='The Url to agents profile photo'
    )
    position = models.TextField(
        null=True,
        help_text='Get the position of a contact'
    )
    url_slug = models.TextField(
        null=True,
        help_text='The property agent profile url identifier used to know '
                  'which agent profile to display'
    )

    class Meta:

        unique_together = (
            (
                'e_mail',
                'fax_number',
                'full_name',
                'home_phone_number',
                'mobile_phone_number',
                'office_phone_number',
                'photo',
                'position',
                'url_slug',
            ),
        )


class Attribute(models.Model):

    display_name = models.TextField(
        null=True,
        help_text='The name of the attribute, in a form suitable for '
                  'displaying to users. Not required when selling or editing.'
    )
    display_value = models.TextField(
        null=True,
        help_text='The value of the attribute as it needs to be displayed to '
                  'the end users'
    )
    name = models.TextField(
        null=True,
        help_text='A name which uniquely identifies the attribute. Required '
                  'when selling or editing.'
    )
    value = models.TextField(
        null=True,
        help_text='The string value of the attribute. When listing, the valid'
                  ' values for the attribute can be determined using the '
                  '“Retrieve attributes for a category” API. Use “false” or '
                  '“true” for boolean attributes. Required when selling or '
                  'editing.'
    )

    class Meta:

        unique_together = (
            (
                'display_name',
                'display_value',
                'name',
                'value',
            ),
        )


class Branding(models.Model):

    background_color = models.TextField(
        null=True,
        help_text='Banner outline/stroke colour, tick the checkbox before '
                  'saving to apply the new colour'
    )
    disable_banner = models.NullBooleanField(
        null=True,
        help_text='Disable the agent branding regardless of Super Feature '
                  'status'
    )
    large_banner_url = models.TextField(
        null=True,
        help_text='The url of a larger version of the logo'
    )
    large_square_logo = models.TextField(
        null=True,
        help_text='A large square branding image with dimensions of 480×480.'
    )
    large_wide_logo = models.TextField(
        null=True,
        help_text='A large rectangular branding image with dimensions of '
                  '480×200.'
    )
    office_location = models.TextField(
        null=True,
        help_text='The name of the office location'
    )
    stroke_color = models.TextField(
        null=True,
        help_text='Banner text colour, tick the checkbox before saving to '
                  'apply the new colour'
    )
    text_color = models.TextField(
        null=True,
        help_text='Banner background colour, tick the checkbox before saving '
                  'to apply the new colour'
    )

    class Meta:

        unique_together = (
            (
                'background_color',
                'disable_banner',
                'large_banner_url',
                'large_square_logo',
                'large_wide_logo',
                'office_location',
                'stroke_color',
                'text_color',
            ),
        )


class BroadbandTechnology(models.Model):

    availability = models.TextField(
        null=True,
        help_text='The availability of the broadband technology.'
    )
    completion = models.TextField(
        null=True,
        help_text='The estimated completion date of planned or underway '
                  'connections.'
    )
    max_down = models.FloatField(
        null=True,
        help_text='The maxiumum download speed (in megabits per second).'
    )
    max_up = models.FloatField(
        null=True,
        help_text='The maximum upload speed (in megabits per second).'
    )
    min_down = models.FloatField(
        null=True,
        help_text='The minimum download speed (in megabits per second).'
    )
    min_up = models.FloatField(
        null=True,
        help_text='The minimup upload speed (in megabits per second).'
    )
    name = models.TextField(
        help_text='The technology name.'
    )

    class Meta:

        unique_together = (
            (
                'availability',
                'completion',
                'max_down',
                'max_up',
                'min_down',
                'min_up',
                'name',
            ),
        )


class EmbeddedContent(models.Model):

    matterport_key = models.TextField(
        null=True,
        help_text='The Matterport video key for the listing’s InsideView '
                  'content.'
    )
    you_tube_video_key = models.TextField(
        null=True,
        help_text='The YouTube video key for the listing.'
    )

    class Meta:

        unique_together = (
            (
                'matterport_key',
                'you_tube_video_key',
            ),
        )


class FlatmateInformation(models.Model):

    current_flatmates = models.TextField(
        null=True,
        help_text='A description of the current flatmates.'
    )
    flatmates = models.IntegerField(
        help_text='The number of current flatmates.'
    )

    class Meta:

        unique_together = (
            (
                'current_flatmates',
                'flatmates',
            ),
        )


class GeographicLocation(models.Model):

    accuracy = models.IntegerField(
        choices=(
            (0, 'None'),
            (1, 'Address'),
            (3, 'Street'),
            (2, 'Suburb'),
        ),
        null=True,
        help_text='The accuracy of the geographic location (address, street '
                  'or suburb).'
    )
    latitude = models.FloatField(
        null=True,
        help_text='The latitude of the location, in degrees (WGS84).'
    )
    longitude = models.FloatField(
        null=True,
        help_text='The longitude of the location, in degrees (WGS84).'
    )

    class Meta:

        unique_together = (
            (
                'accuracy',
                'latitude',
                'longitude',
            ),
        )


class ListingType(enum.Enum):

    PROPERTY = enum.auto()
    FLATMATE = enum.auto()


class Listing(models.Model):

    listing_id = models.IntegerField(
        primary_key=True,
        help_text='The ID of the listing.',
    )
    listing_type = EnumIntegerField(
        ListingType,
        help_text='Type of listing(property, flatmate, etc.)',
    )
    agency_reference = models.TextField(

rentme/raw/importer/models.py
from django.db import models


class CachedResponse(models.Model):

    class Meta:
        unique_together = (
            ('method', 'url', 'kwargs')
        )

    method = models.CharField(max_length=10)
    url = models.TextField()
    kwargs = models.TextField()

    content = models.BinaryField()
    data = models.TextField()

    expiry = models.DateTimeField()

rentme/raw/models/base.py
import datetime
import json

from django.db import models


class JSONEncoder(json  .JSONEncoder):
    include_nulls = False

    def default(self, o):
        if isinstance(o, RawModel):
            dikt = {}
            for attr, stype in o.swagger_types.items():
                value = getattr(o, attr)
                if value is None and not self.include_nulls:
                    continue
                elif stype.startswith('list['):
                    value = list(value.all())
                attr = o.attribute_map[attr]
                dikt[attr] = value
            return dikt
        elif isinstance(o, datetime.datetime):
            return o.isoformat()
        return super().default(o)


class RawModel(models.Model):

    last_updated = models.DateTimeField(auto_now=True)

    class Meta:

        abstract = True

    def __repr__(self):
        return json.dumps(self, indent=2, cls=JSONEncoder)

rentme/api/views.py
# from rest_framework import authentication, generics, mixins, permissions, viewsets
# from rest_framework.response import Response
# from rest_framework.views import APIView
#
# from rentme.api.serializers import AgencySerializer, ListingShortSerializer
# from rentme.data.models.listing import Agency, Listing
#
#
# class HealthcheckView(APIView):
#     permissions = (permissions.AllowAny, )
#
#     def get(self, request, format=None):
#         return Response({})
#
#
# class ListingViewSet(viewsets.ReadOnlyModelViewSet):
#
#     queryset = Listing.objects.all().order_by('listing_id')
#     serializer_class = ListingShortSerializer
#     lookup_field = 'listing_id'
#     lookup_value_regex = '[1-9][0-9]*'
#
#
# class AgencyViewSet(viewsets.ReadOnlyModelViewSet):
#
#     queryset = Agency.objects.all().order_by('id')
#     serializer_class = AgencySerializer
#     lookup_field = 'id'
#     lookup_value_regex = '[1-9][0-9]*'

rentme/data/views.py
from django.http import JsonResponse, HttpResponse
from django.shortcuts import redirect
from django.views.generic import DetailView, ListView
from django.views.generic.list import BaseListView

from rentme.data import api, models
# from rentme.data.importer import catalogue


class LocalityView(ListView):
    model = models.catalogue.Locality
    template_name = 'rentme/locality_list.html'
    context_object_name = 'localities'


class LocalityDrilldownView(ListView):

    model = models.catalogue.Locality
    template_name = 'rentme/listings_all.html'
    context_object_name = 'listing_list'
    paginate_by = 20

    def get_queryset(self):
        qs = super().get_queryset()
        # if hasattr(self, 'locality_id'):
        #     qs = qs.filter(suburb__district__listing_id=int(self.locality_id))
        # if hasattr(self, 'district_id'):
        #     qs = qs.filter(suburb__district_id=int(self.district_id))
        if hasattr(self, 'suburb_id'):
            qs = qs.filter(suburb_id=int(self.district_id))
        return qs


class RentalListView(ListView):
    model = models.listings.Listing
    template_name = 'rentme/listings_all.html'
    context_object_name = 'listing_list'

    def get_queryset(self):
        suburbs = models.catalogue.Suburb.objects.filter(district_id__in=(47, 46, 45, 44))
        from pprint import pprint
        pprint(list(suburbs))

        qs = super().get_queryset()
        qs = qs.filter(rent_per_week__lt=500, rent_per_week__gt=200)
        qs = qs.filter(suburb__in=suburbs)
        pprint(list(qs))
        return qs


class RentalView(DetailView):
    template_name = 'rentme/listing_single.html'
    model = models.listings.Listing

rentme/web/views.py
import django.http
from django.shortcuts import redirect
from django.views.generic import ListView


from rentme.celery import catalogue
from rentme.web import api, models


class LocalityView(ListView):
    model = models.catalogue.Locality
    template_name = 'rentme/locality_list.html'
    context_object_name = 'localities'


def load_all_base_data(request):
    catalogue.reload_localities.apply_async()
    catalogue.reload_categories.apply_async()
    catalogue.reload_membership_localities.apply_async()
    return redirect('home')


def load_search_rentals(request):
    kwargs = {key: val for key, val in request.GET.items()}
    x = api.search_rentals(**kwargs)
    return django.http.response.HttpResponse('Loaded ' + str(len(x)) +
                                             ' properties')


def load_rental(request, id):
    # x = api.load_rental(id)
    return django.http.response.HttpResponse('Loaded property')

rentme/data/templates/rentme/_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load staticfiles %}
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    {% block bootstrap %}
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap-theme.min.css' %}" />
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}" />
    <script src="{% static 'jquery-2.1.4.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    {% endblock %}
    {% block head %}
    <link rel="stylesheet" href="{% static 'styles.css' %}" />
    {% endblock %}
    {% block head_files %}
    {% if maps %}
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ol3/3.7.0/ol.css" type="text/css" />
        <script src="https://cdnjs.cloudflare.com/ajax/libs/ol3/3.7.0/ol.js"></script>
    {% endif %}
    {% if lightbox %}
        <link rel="stylesheet" href="{% static 'blueimp-gallery/css/blueimp-gallery.min.css' %}">
    {% endif %}
    {% endblock %}
</head>
<body>
    {% block body %}
    <div class="container">
        {% block content %}{% endblock %}
    </div>
    {% if lightbox %}
    <div style="display: none;" id="blueimp-gallery" class="blueimp-gallery blueimp-gallery-controls">
        <!-- The container for the modal slides -->
        <div style="width: 192000px;" class="slides"></div>
        <!-- Controls for the borderless lightbox -->
        <h3 class="title">Ghost from the past</h3>
        <a class="prev">‹</a>
        <a class="next">›</a>
        <a class="close">×</a>
        <a class="play-pause"></a>
        <ol class="indicator"></ol>
    </div>
    <script src="{% static 'blueimp-gallery/js/blueimp-gallery.min.js' %}"></script>
    <script>
        $(function() {
            $('.lightbox a').on('click', function() {
                blueimp.Gallery(
                        $(this).children('a'),
                        {container: '#blueimp-gallery', carousel: true})
            });
        });
    </script>
    {% endif %}
    {% endblock %}
</body>
</html>

rentme/data/templates/rentme/listing_single.html
{% extends 'rentme/_base.html' %}
{% load static %}

{% block head_files %}
    {% with maps=1 %}
        {{ block.super }}
    {% endwith %}
{% endblock %}

{% block title %}TradeMe Listing -- {{listing.title}}{% endblock %}

{% block content %}
{% debug %}
<div class="page-header">
  <h1>{{listing.title}} <small>${{ listing.rent_per_week }}/week &mdash; {{listing.address|default:""}}</small></h1>
  <h2>{{ listing.suburb.district.locality.name }} &rarr; {{ listing.suburb.district.name }} &rarr; {{ listing.suburb.name }}</h2>
</div>
<div class="row">
    <div class="col-sm-12 col-md-6">
{% include 'rentme/incl/listing_gallery.html' with photos=listing.photos.all carousel=1 only %}
    </div>
    <div class="col-sm-12 col-md-6">
        <div>
            {{listing.description|default:"No description available"|linebreaks}}
        </div>
        <div class="btn-toolbar text-center" role="toolbar">
{% include 'rentme/incl/listing_rating_pills.html' with listing=listing only %}
            <div class="btn-group pull-right" role="group">
                <a href="{{listing.trademe_url}}" class="btn btn-default">
                    <span class="glyphicon glyphicon-globe"></span>
                    View on TradeMe
                </a>
            </div>
        </div>
    </div>
    {% if listing.attributes %}
    <div class="col-sm-12 col-md-6">
        <table class="table">
        <caption>Property Attributes</caption>
        <thead>
            <tr>
                <th>Name</th>
                <th>Value</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>Listed on</td>
                <td>{{ listing.start_date }}</td>
            </tr>
            {% for attribute in listing.attributes.all %}
            <tr>
                <td>{{ attribute.display_name }}</td>
                <td>{{ attribute.value }}</td>
            </tr>
            {% endfor %}
        </tbody>
        </table>
    </div>
    {% endif %}
</div>
<div class="clearfix"></div>

    {% if listing.location %}
    <div class="panel panel-default">
    <div class="panel-heading">Location</div>
    <div>
        {% include 'rentme/incl/map_with_marker.html' with point=listing.location only %}
    </div>
    </div>
    {% endif %}

<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">Rate this property</h3>
    </div>
    <div>
        {{listing.location.get_accuracy_display}}
        TODO: Write this form.
    </div>
</div>

{% if similar_location_photos %}
<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">Photos for properties at this location</h3>
    </div>
    <div>
        {% include 'rentme/incl/listing_gallery.html' with photos=similar_location_photos only %}
    </div>
</div>
{% endif %}

{% if similar_location_listings %}
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Other properties at the same location</h3>
  </div>
    <div class="list-group">
    {% for rel_listing in similar_location_listings %}
        {% include 'rentme/incl/listing_list_item.html' with listing=rel_listing only %}
    {% endfor %}
    </div>
</div>
{% endif %}
{% endblock %}

rentme/data/templates/rentme/listings_all.html
{% extends 'rentme/_base.html' %}

{% block title %}All imported listings{% if extra_title %} - {{ extra_title }}{% endif %}{% endblock %}

{% block content %}
<div class="list-group">
{% for listing in listing_list %}
    {% include 'rentme/incl/listing_list_item.html' with listing=listing only %}
{% endfor %}
</div>
{% endblock %}

rentme/data/templates/rentme/locality_list.html
<html>
<head>
    <title>All locality</title>
    <style>

    .links line {
      stroke: #999;
      stroke-opacity: 0.6;
    }

    .nodes circle {
      stroke: #fff;
      stroke-width: 1.5px;
    }

    </style>
</head>
<body>
<svg width="960" height="600"></svg>
<script src="https://d3js.org/d3.v4.min.js"></script>
<script>

var svg = d3.select("svg"),
    width = +svg.attr("width") / 2,
    height = +svg.attr("height") / 2;

var simulation = d3.forceSimulation()
    .force("link", d3.forceLink().id(function(d) { return d.id; }))
    .force("charge", d3.forceManyBody())
    .force("center", d3.forceCenter(width, height));

function hash_string(str) {
  if (str) {
    return (str
            .split('')
            .map(function (char) {return char.charCodeAt(0)})
            .reduce(function(a, b) {return a + 7 * (13 + b)}))
  } else {
    return 696969;
  }
}
function color(string) {
  var hash = fNaN(hash_string(string))
  var SAT_RANGE = 20
  var LIGHT_RANGE = 20
  var saturation = 50 + (hash % SAT_RANGE)
  hash = ~~(hash / SAT_RANGE)
  var lightness = 50 + (hash % LIGHT_RANGE)
  hash = ~~(hash / LIGHT_RANGE)
  var hue = fNaN(hash % 360)
  return "hsl(" + hue + ", " + saturation + "%, " + lightness + "%)";
}

const fNaN = (f) => {
  if (isNaN(f)) {
    throw Exception("Value is NaN")
  }
  return f
}


d3.json("localities.json", function(error, graph) {
  if (error) throw error;

  var link = svg.append("g")
      .attr("class", "links")
    .selectAll("line")
    .data(graph.links)
    .enter().append("line")
      .attr("stroke-width", 2);

  var MIN_RADIUS = 1;
  var MAX_RADIUS = 5;
  var node_sizes = graph.nodes.map(function (node) { return node.listings });
  var scale_factor = (MAX_RADIUS - MIN_RADIUS) / (node_sizes.reduce((a, b) => Math.max(a, b)) - node_sizes.reduce((a, b) => Math.min(a, b)))

  var node = svg.append("g")
      .attr("class", "nodes")
    .selectAll("circle")
    .data(graph.nodes)
    .enter().append("circle")
      .attr("r", (d) => fNaN(MIN_RADIUS + (d.listings * scale_factor) ))
      .attr("fill", (d) => color(d.group))
      .call(d3.drag()
          .on("start", dragstarted)
          .on("drag", dragged)
          .on("end", dragended));

  node.append("title")
      .text((d) => d.name + " - " + d.listings);

  simulation
      .nodes(graph.nodes)
      .on("tick", ticked);

  simulation.force("link")
      .links(graph.links);

  function ticked() {
    link
        .attr("x1", function(d) { return d.source.x; })
        .attr("y1", function(d) { return d.source.y; })
        .attr("x2", function(d) { return d.target.x; })
        .attr("y2", function(d) { return d.target.y; });

    node
        .attr("cx", function(d) { return d.x; })
        .attr("cy", function(d) { return d.y; });
  }
});

function dragstarted(d) {
  if (!d3.event.active) simulation.alphaTarget(0.3).restart();
  d.fx = d.x;
  d.fy = d.y;
}

function dragged(d) {
  d.fx = d3.event.x;
  d.fy = d3.event.y;
}

function dragended(d) {
  if (!d3.event.active) simulation.alphaTarget(0);
  d.fx = null;
  d.fy = null;
}

</script>


<ul>
    {% for locality in localities.all %}
    <li>
        <b>L{{locality.pk}}L</b> {{locality.name}}
        <ul>
            {% for district in locality.districts.all %}
            <li>
                <b>D{{district.pk}}D</b> {{district.name}}
                <ul>
                    {% for suburb in district.suburbs.all %}
                    <li><b>S{{suburb.pk}}S</b> {{suburb.name}} <i>{{ suburb.listings.count }}</i></li>
                    {% endfor %}
                </ul>
            </li>
            {% endfor %}
        </ul>
    </li>
    {% endfor %}
</ul>
</body>
</html>